"""Check the baked model files against a manifest of their checksums.

`joblib.load` is `pickle.load`, and unpickling runs whatever the file tells it
to. The `.pkl` files under `backend/seed/models/` are committed to a public
repository, so "a pull request edits a model file" and "a pull request runs code
on the deploy host" are the same sentence. Nothing about a pickle looks wrong
until it has already executed.

The manifest is the fix. The seed models are checked before they are copied into
the model directory, which is the one boundary a repository-supplied file has to
cross to reach `joblib.load`. Models written by a retrain never cross it and are
not checked - they were produced by this process, not shipped to it.

That means changing a seed model is a two-file change: the `.pkl` and its
recorded hash, side by side in the same diff. It does not stop a maintainer who
means it. It does stop a model file changing quietly.

    python scripts/verify_seed_models.py           # check, exit 1 on mismatch
    python scripts/verify_seed_models.py --write   # re-record after a legitimate change
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

SEED_MODELS = Path(__file__).resolve().parent.parent / "seed" / "models"
MANIFEST = SEED_MODELS / "SHA256SUMS"

# Only the pickles. metrics.json and importances.json are data the app reads and
# renders, never code it executes.
PATTERN = "*.pkl"


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def current() -> dict:
    return {p.name: digest(p) for p in sorted(SEED_MODELS.glob(PATTERN))}


def recorded() -> dict:
    if not MANIFEST.exists():
        return {}
    out = {}
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        h, name = line.split(None, 1)
        out[name.strip()] = h
    return out


def write() -> int:
    lines = [
        "# sha256 of every baked model file. Generated by scripts/verify_seed_models.py.",
        "# Regenerate with --write, and only in the same commit that changes a model.",
    ]
    files = current()
    lines += [f"{h}  {name}" for name, h in files.items()]
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"recorded {len(files)} model files in {MANIFEST}")
    return 0


def check() -> int:
    have, want = current(), recorded()

    if not want:
        print(f"ERROR: no manifest at {MANIFEST}", file=sys.stderr)
        print("Generate one with: python scripts/verify_seed_models.py --write", file=sys.stderr)
        return 1

    problems = []
    for name in sorted(set(have) | set(want)):
        if name not in want:
            problems.append(f"  {name}: present but not in the manifest")
        elif name not in have:
            problems.append(f"  {name}: in the manifest but missing from disk")
        elif have[name] != want[name]:
            problems.append(f"  {name}: CHECKSUM MISMATCH")

    if problems:
        print("ERROR: the baked models do not match their manifest.", file=sys.stderr)
        print("\n".join(problems), file=sys.stderr)
        print(
            "\nA pickle is executable. Refusing to load these. If the change was\n"
            "intended, re-record it with --write in the same commit.",
            file=sys.stderr,
        )
        return 1

    print(f"verified {len(have)} baked model files against {MANIFEST.name}")
    return 0


if __name__ == "__main__":
    sys.exit(write() if "--write" in sys.argv[1:] else check())
